name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: 盐焗乳鸽还要香锅
          password: ${{ secrets.PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.cn-beijing.aliyuncs.com/strk2/dockerlearn:latest
  pull-docker:
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker login --username=盐焗乳鸽还要香锅 --password-stdin=${{ secrets.PASSWORD }} registry.cn-beijing.aliyuncs.com
            docker pull registry.cn-beijing.aliyuncs.com/strk2/dockerlearn:latest
            docker run -d -p 8083:4000 registry.cn-beijing.aliyuncs.com/strk2/dockerlearn:latest
