name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      run: 
        docker version

        docker login --username=盐焗乳鸽还要香锅 --password=${{ secrets.PASSWORD }} registry.cn-beijing.aliyuncs.com
        cd dockerlearn
       
        docker build . --file Dockerfile --tag registry. cn-beijing.aliyuncs.com/dockerlearn

          
        docker push registry.registry.cn-beijing.aliyuncs.com/dockerlearn
        echo 'succeed'
          

        
      
