name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Login to registry
      uses: docker/login-action@v1
      with:
          registry: registry.cn-beijing.aliyuncs.com
          username: 盐焗乳鸽还要香锅
          password: ${{ secrets.PASSWORD }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: registry.cn-beijing.aliyuncs.com/strk2/dockerlearn:latest


        
      
