name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - uses: easingthemes/ssh-deploy@v2.0.7
      with:
        host: ${{secrets.TOKEN}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        port: ${{secrets.PORT}}
        script: |
          cd /var/lib/docker/actionsTest
          docker run -d --name test-action -p 8083:8080 test
          
          
        
      
